"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { Food, foodsApi } from "../../../lib/productApi";
import { FoodIcon, PlusIcon, SearchIcon, TrashIcon } from "../../../components/UiIcons";

export default function Foods(){
 const[foods,setFoods]=useState<Food[]>([]),[q,setQ]=useState(""),[error,setError]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState(""),[creating,setCreating]=useState(false);
 const load=useCallback(async()=>{setLoading(true);setError("");try{setFoods((await foodsApi.list()).foods)}catch(e){setError(e instanceof Error?e.message:"Could not load foods")}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);
 async function search(e:FormEvent){e.preventDefault();if(!q.trim()){await load();return}setLoading(true);setError("");setMessage("");try{setFoods((await foodsApi.search(q)).foods);setMessage(`Showing matches for “${q}”`)}catch(e){setError(e instanceof Error?e.message:"Search failed")}finally{setLoading(false)}}
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;setSaving(true);setError("");try{const f=new FormData(form);await foodsApi.create({name:f.get("name"),servingLabel:f.get("servingLabel"),calories:Number(f.get("calories")),proteinG:Number(f.get("proteinG")),carbsG:Number(f.get("carbsG")),fatG:Number(f.get("fatG"))});form.reset();setCreating(false);setMessage("Custom food saved to your library");await load()}catch(e){setError(e instanceof Error?e.message:"Could not save food")}finally{setSaving(false)}}
 return <main className="product-page foods-page">
  <section className="page-heading"><div><p className="eyebrow">Your nutrition library</p><h1>Foods</h1><p>Find trusted foods or save the meals you know best.</p></div><button className="primary-action" onClick={()=>setCreating(true)}><PlusIcon/> Create food</button></section>
  {error&&<p className="alert-card" role="alert">{error} <button onClick={()=>void load()}>Retry</button></p>}{message&&<p className="success-card" role="status">{message}</p>}
  <section className="food-search-hero"><div className="food-search-copy"><span className="visual-bubble"><FoodIcon/></span><div><h2>What are you looking for?</h2><p>Search verified foods and your personal collection.</p></div></div><form className="library-search" onSubmit={search}><SearchIcon/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Try chicken rice, oat milk…" aria-label="Search foods"/><button>Search</button></form><div className="search-shortcuts"><span>Quick ideas</span>{["Breakfast","Chicken","Rice","Fruit"].map(x=><button key={x} onClick={()=>setQ(x)}>{x}</button>)}</div></section>
  <section className="section-heading"><div><h2>{q?"Search results":"My foods"}</h2><p>{loading?"Loading your library…":`${foods.length} ${foods.length===1?"food":"foods"}`}</p></div>{q&&<button className="text-action" onClick={()=>{setQ("");setMessage("");void load()}}>Clear search</button>}</section>
  {!loading&&foods.length===0?<section className="visual-empty"><div className="empty-illustration"><FoodIcon/><span>+</span></div><h2>{q?"No foods found":"Build your food library"}</h2><p>{q?"Try a broader search, or create this food yourself.":"Save foods you eat often for faster diary entries."}</p><button className="primary-action" onClick={()=>setCreating(true)}><PlusIcon/> Create a custom food</button></section>:<div className="food-grid">{foods.map(food=><article className="food-card" key={food.id}><div className="food-card-top"><span className="food-avatar large"><FoodIcon/></span><div><h3>{food.name}</h3><p>{food.brand?`${food.brand} · `:""}{food.servingLabel}</p></div>{food.verified&&<span className="verified-badge">Verified</span>}</div><div className="food-calories"><strong>{Math.round(food.calories)}</strong><span>kcal</span></div><div className="food-macros"><span className="protein"><b>{Math.round(food.proteinG)}g</b> Protein</span><span className="carbs"><b>{Math.round(food.carbsG)}g</b> Carbs</span><span className="fat"><b>{Math.round(food.fatG)}g</b> Fat</span></div><footer><Link href="/diary">Add in diary</Link>{food.source==="CUSTOM"&&<button aria-label={`Delete ${food.name}`} onClick={async()=>{await foodsApi.remove(food.id);setMessage(`${food.name} removed`);await load()}}><TrashIcon/></button>}</footer></article>)}</div>}
  {creating&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setCreating(false)}}><section className="sheet-modal" role="dialog" aria-modal="true" aria-labelledby="create-food-title"><header><div><p className="eyebrow">Personal library</p><h2 id="create-food-title">Create custom food</h2></div><button className="icon-close" aria-label="Close" onClick={()=>setCreating(false)}>×</button></header><form className="modern-form" onSubmit={create}><label>Food name<input name="name" placeholder="e.g. Mum’s chicken curry" required/></label><label>Serving description<input name="servingLabel" placeholder="e.g. 1 bowl (320 g)" required/></label><div className="nutrition-grid">{[["calories","Calories"],["proteinG","Protein (g)"],["carbsG","Carbs (g)"],["fatG","Fat (g)"]].map(([n,l])=><label key={n}>{l}<input name={n} type="number" min="0" step="0.01" required/></label>)}</div><div className="form-note"><FoodIcon/><p>This food stays in your personal library. Saving it does not use AI.</p></div><button className="primary-action full" disabled={saving}>{saving?"Saving…":"Save custom food"}</button></form></section></div>}
 </main>
}
