"use client";

import { ChangeEvent, FormEvent, useCallback, useEffect, useRef, useState } from "react";
import { analyzePhoto, deletePhoto, Food, foodsApi, PhotoAnalysis, privatePhotoUrl, uploadPhoto } from "../../../lib/productApi";
import { createDiaryEntry, deleteDiaryEntry, getDaySummary, isoDay, updateDiaryEntry } from "../../../lib/tracking";
import { diaryItemsForEdit } from "../../../lib/product";
import { CameraIcon, ChevronIcon, EditIcon, FoodIcon, PlusIcon, SearchIcon, SparkIcon, TrashIcon } from "../../../components/UiIcons";

type Item={id?:string;foodId?:string;name:string;servingLabel:string;calories:number;proteinG:number;carbsG:number;fatG:number;servings:number};
type Entry={id:string;mealType:string;title?:string;notes?:string;hasPhoto?:boolean;analysisStatus?:string;items:Item[]};
const meals=[{id:"BREAKFAST",label:"Breakfast",emoji:"☀️"},{id:"LUNCH",label:"Lunch",emoji:"🥗"},{id:"DINNER",label:"Dinner",emoji:"🌙"},{id:"SNACK",label:"Snacks",emoji:"🍓"}];
const blank={name:"",servingLabel:"serving",calories:0,proteinG:0,carbsG:0,fatG:0};
const entryCalories=(entry:Entry)=>Math.round(entry.items.reduce((sum,item)=>sum+item.calories*item.servings,0));
const prettyDay=(day:string)=>new Intl.DateTimeFormat("en",{weekday:"short",month:"short",day:"numeric"}).format(new Date(`${day}T12:00:00`));

export default function Diary(){
 const[day,setDay]=useState(()=>isoDay(new Date())),[entries,setEntries]=useState<Entry[]>([]),[goals,setGoals]=useState({calories:0,proteinG:0,carbsG:0,fatG:0,waterMl:0}),[totals,setTotals]=useState({calories:0,proteinG:0,carbsG:0,fatG:0,waterMl:0,exerciseCalories:0,exerciseMinutes:0}),[error,setError]=useState(""),[notice,setNotice]=useState(""),[loading,setLoading]=useState(true),[editing,setEditing]=useState<Entry|null>(null),[food,setFood]=useState<Food|null>(null),[results,setResults]=useState<Food[]>([]),[query,setQuery]=useState(""),[composerMeal,setComposerMeal]=useState<string|null>(null),[photoEntry,setPhotoEntry]=useState<Entry|null>(null),[analysis,setAnalysis]=useState<PhotoAnalysis|null>(null),[analyzing,setAnalyzing]=useState(false),[uploading,setUploading]=useState(false);
 const cameraRef=useRef<HTMLInputElement>(null),galleryRef=useRef<HTMLInputElement>(null);
 const load=useCallback(async()=>{setLoading(true);setError("");try{const data=await getDaySummary(day);setEntries(data.diaryEntries as Entry[]);setGoals(data.goals);setTotals(data.totals)}catch(e){setError(e instanceof Error?e.message:"Could not load diary")}finally{setLoading(false)}},[day]);
 useEffect(()=>{void load()},[load]);
 const move=(n:number)=>{const d=new Date(day+"T12:00:00");d.setDate(d.getDate()+n);setDay(isoDay(d))};
 async function search(e:FormEvent){e.preventDefault();setError("");try{setResults((await foodsApi.search(query)).foods)}catch(e){setError(e instanceof Error?e.message:"Search failed")}}
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const item={...(food?{foodId:food.id}:{}),name:food?.name||String(f.get("name")),servings:Number(f.get("servings")),servingLabel:food?.servingLabel||String(f.get("servingLabel")),calories:food?.calories??Number(f.get("calories")),proteinG:food?.proteinG??Number(f.get("proteinG")),carbsG:food?.carbsG??Number(f.get("carbsG")),fatG:food?.fatG??Number(f.get("fatG"))};try{const body={date:day,mealType:f.get("mealType"),title:f.get("title")||undefined,notes:f.get("notes")||undefined,items:editing?diaryItemsForEdit(editing.items,item):[item]};editing?await updateDiaryEntry(editing.id,body):await createDiaryEntry(body);setEditing(null);setComposerMeal(null);setFood(null);setResults([]);setNotice(editing?"Entry updated":"Food added to your diary");await load()}catch(e){setError(e instanceof Error?e.message:"Save failed")}}
 async function choosePhoto(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;setUploading(true);setError("");try{let target=photoEntry;if(!target){const created=await createDiaryEntry({date:day,mealType:"SNACK",title:"Photo meal",items:[]}) as {entry:Entry};target=created.entry}await uploadPhoto(target.id,file);setPhotoEntry({...target,hasPhoto:true});setAnalysis(null);setNotice("Photo saved privately. AI analysis is off until you choose it.");await load()}catch(e){setError(e instanceof Error?e.message:"Could not attach photo")}finally{setUploading(false);e.target.value=""}}
 async function requestAnalysis(){if(!photoEntry)return;setAnalyzing(true);setError("");try{setAnalysis((await analyzePhoto(photoEntry.id)).analysis)}catch(e){setError(e instanceof Error?e.message:"Could not analyze photo")}finally{setAnalyzing(false)}}
 function closePanels(){setEditing(null);setComposerMeal(null);setFood(null);setResults([])}
 const remaining=Math.round(goals.calories-totals.calories+totals.exerciseCalories),pct=goals.calories?Math.min(100,Math.round(totals.calories/goals.calories*100)):0;
 return <main className="product-page diary-page">
  <section className="page-heading"><div><p className="eyebrow">Daily nutrition</p><h1>Food diary</h1><p>Capture what you eat, your way.</p></div><button className="primary-action" onClick={()=>setComposerMeal("BREAKFAST")}><PlusIcon/> Add food</button></section>
  <section className="diary-overview">
   <div className="date-switcher"><button aria-label="Previous day" onClick={()=>move(-1)}><ChevronIcon className="flip"/></button><div><strong>{prettyDay(day)}</strong><span>{day===isoDay(new Date())?"Today":"Daily diary"}</span></div><button aria-label="Next day" onClick={()=>move(1)}><ChevronIcon/></button></div>
   <div className="calorie-orbit" style={{"--progress":`${pct*3.6}deg`} as React.CSSProperties}><div><strong>{Math.max(0,remaining)}</strong><span>kcal left</span></div></div>
   <div className="macro-overview"><span><b>{Math.round(totals.calories)}</b> eaten</span><span><b>{goals.calories}</b> goal</span><span><b>{Math.round(totals.exerciseCalories)}</b> exercise</span></div>
  </section>
  {error&&<p className="alert-card" role="alert">{error}</p>}{notice&&<p className="success-card" role="status">{notice}</p>}
  <section className="photo-capture-card">
   <div className="capture-visual"><CameraIcon/><span><SparkIcon/> AI optional</span></div>
   <div><p className="eyebrow">Meal photo</p><h2>Snap it now. Log it your way.</h2><p>Save a private meal photo first. If you want help estimating the food later, you can explicitly ask AI—nothing is analyzed automatically.</p><div className="capture-actions"><button className="primary-action" onClick={()=>{setPhotoEntry(null);cameraRef.current?.click()}}><CameraIcon/> Take photo</button><button className="secondary-action" onClick={()=>{setPhotoEntry(null);galleryRef.current?.click()}}>Choose from library</button></div></div>
   <input ref={cameraRef} className="visually-hidden" type="file" accept="image/jpeg,image/png,image/webp" capture="environment" onChange={choosePhoto}/><input ref={galleryRef} className="visually-hidden" type="file" accept="image/jpeg,image/png,image/webp" onChange={choosePhoto}/>
  </section>
  <div className="meal-stack">{meals.map(meal=>{const group=entries.filter(e=>e.mealType===meal.id),cal=group.reduce((n,e)=>n+entryCalories(e),0);return <section className="meal-card" key={meal.id}><header><div className="meal-title"><span>{meal.emoji}</span><div><h2>{meal.label}</h2><p>{group.length?`${group.length} ${group.length===1?"entry":"entries"}`:"Nothing logged yet"}</p></div></div><div className="meal-header-actions"><strong>{cal} kcal</strong><button aria-label={`Add ${meal.label}`} onClick={()=>{setEditing(null);setComposerMeal(meal.id)}}><PlusIcon/></button></div></header>{group.length===0?<button className="empty-meal" onClick={()=>setComposerMeal(meal.id)}><PlusIcon/><span>Add your first item</span></button>:<div className="entry-list">{group.map(entry=><article className="entry-row" key={entry.id}>{entry.hasPhoto?<button className="entry-photo" onClick={()=>{setPhotoEntry(entry);setAnalysis(null)}} aria-label={`Open photo for ${entry.title||entry.items[0]?.name||"meal"}`}><img src={privatePhotoUrl(entry.id)} alt="Your private meal"/></button>:<div className="food-avatar"><FoodIcon/></div>}<div className="entry-main"><strong>{entry.title||entry.items[0]?.name||"Meal photo"}</strong><span>{entry.items.map(i=>i.name).filter(Boolean).join(", ")||"Photo waiting for details"}</span><div className="macro-pills"><i>P {Math.round(entry.items.reduce((n,i)=>n+i.proteinG*i.servings,0))}g</i><i>C {Math.round(entry.items.reduce((n,i)=>n+i.carbsG*i.servings,0))}g</i><i>F {Math.round(entry.items.reduce((n,i)=>n+i.fatG*i.servings,0))}g</i></div></div><strong className="entry-calories">{entryCalories(entry)}<small>kcal</small></strong><div className="row-actions"><button aria-label="Edit entry" onClick={()=>{setEditing(entry);setComposerMeal(entry.mealType);setFood(null)}}><EditIcon/></button><button aria-label="Delete entry" onClick={async()=>{await deleteDiaryEntry(entry.id);await load()}}><TrashIcon/></button></div></article>)}</div>}</section>})}</div>
  {(composerMeal||editing)&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)closePanels()}}><section className="sheet-modal" role="dialog" aria-modal="true" aria-labelledby="food-dialog-title"><header><div><p className="eyebrow">{editing?"Update diary":"New entry"}</p><h2 id="food-dialog-title">{editing?"Edit food":"Add food"}</h2></div><button className="icon-close" onClick={closePanels} aria-label="Close">×</button></header><form className="modern-form" onSubmit={save}><label className="search-field"><SearchIcon/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search your food library"/><button type="button" onClick={search}>Search</button></label>{results.length>0&&<div className="search-results">{results.map(x=><button type="button" key={x.id} onClick={()=>{setFood(x);setResults([])}}><span><strong>{x.name}</strong><small>{x.servingLabel}</small></span><b>{x.calories} kcal</b></button>)}</div>}<div className="form-grid"><label>Meal<select name="mealType" defaultValue={editing?.mealType||composerMeal||"BREAKFAST"}>{meals.map(m=><option key={m.id} value={m.id}>{m.label}</option>)}</select></label><label>Servings<input name="servings" type="number" min="0.01" step="0.01" defaultValue={editing?.items[0]?.servings||1} required/></label></div><label>Entry title <span className="optional">Optional</span><input name="title" defaultValue={editing?.title}/></label>{food?<div className="selected-food"><FoodIcon/><span><strong>{food.name}</strong><small>{food.servingLabel} · {food.calories} kcal</small></span><button type="button" onClick={()=>setFood(null)}>Change</button></div>:<><label>Food name<input name="name" defaultValue={editing?.items[0]?.name} required/></label><label>Serving label<input name="servingLabel" defaultValue={editing?.items[0]?.servingLabel||"serving"} required/></label><div className="nutrition-grid">{[["calories","Calories"],["proteinG","Protein (g)"],["carbsG","Carbs (g)"],["fatG","Fat (g)"]].map(([n,l])=><label key={n}>{l}<input name={n} type="number" min="0" step="0.01" defaultValue={(editing?.items[0] as any)?.[n]||0} required/></label>)}</div></>}<label>Notes <span className="optional">Optional</span><textarea name="notes" defaultValue={editing?.notes}/></label><button className="primary-action full" type="submit">{editing?"Save changes":"Add to diary"}</button></form></section></div>}
  {photoEntry&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget){setPhotoEntry(null);setAnalysis(null)}}}><section className="sheet-modal photo-sheet" role="dialog" aria-modal="true" aria-labelledby="photo-title"><header><div><p className="eyebrow">Private meal photo</p><h2 id="photo-title">{photoEntry.title||"Meal photo"}</h2></div><button className="icon-close" onClick={()=>{setPhotoEntry(null);setAnalysis(null)}} aria-label="Close">×</button></header>{photoEntry.hasPhoto&&<img className="photo-preview" src={privatePhotoUrl(photoEntry.id)} alt="Your private meal"/>}{!analysis?<div className="ai-choice"><SparkIcon/><div><strong>Want an estimate?</strong><p>AI can suggest foods, portions and nutrition. It may be wrong—you review everything before adding it.</p></div><button className="ai-action" onClick={requestAnalysis} disabled={analyzing}>{analyzing?"Analyzing…":"Analyze with AI"}</button><small>Optional · Your photo is sent only when you tap this button.</small></div>:<div className="analysis-result"><div className="analysis-heading"><span><SparkIcon/> AI suggestion</span><b className={`confidence ${analysis.confidence}`}>{analysis.confidence} confidence</b></div><h3>{analysis.description}</h3><p className="calorie-estimate">{Math.round(analysis.calorieRange.min)}–{Math.round(analysis.calorieRange.max)} kcal estimated</p>{analysis.items.map((item,i)=><div className="analysis-item" key={`${item.name}-${i}`}><span><strong>{item.name}</strong><small>{item.portion}</small></span><b>{Math.round(item.calories)} kcal</b></div>)}<p className="review-note">Review this estimate before using it. AI analysis does not change your diary automatically.</p></div>}<div className="photo-footer"><button className="secondary-action" onClick={()=>galleryRef.current?.click()} disabled={uploading}>Replace photo</button><button className="danger-link" onClick={async()=>{await deletePhoto(photoEntry.id);setPhotoEntry(null);setAnalysis(null);await load()}}>Remove photo</button></div></section></div>}
 </main>
}
