import { Router } from "express";
import { z } from "zod";
import { db } from "../db.js";
import { env } from "../config.js";
import { hashPassword, verifyPassword } from "../auth.js";
import { REGISTRATION_ACCEPTED, REGISTRATION_THROTTLED, preparePendingRegistration } from "../registration.js";
import { createVerificationToken, hashVerificationToken } from "../verification.js";
import { requireUser, type AuthedRequest } from "../middleware/requireUser.js";
import { authenticateVerifiedAccount, verifyPendingAccount } from "../accountAuth.js";
import { createSessionToken, hashSessionToken, SESSION_TTL_MS } from "../session.js";
import { PASSWORD_RESET_ACCEPTED, PASSWORD_RESET_INVALID, requestPasswordReset, resetPassword } from "../passwordRecovery.js";
import { resendDelivery } from "../delivery.js";

export const authRouter=Router();
const credentials=z.object({username:z.string().trim().min(3).max(30).regex(/^[a-zA-Z0-9_]+$/),password:z.string().min(10).max(128),email:z.string().trim().email()});
const loginCredentials=z.object({identity:z.string().trim().min(3).max(254),password:z.string().min(10).max(128)});
const cookie={httpOnly:true,secure:env.NODE_ENV==="production",sameSite:"lax" as const,maxAge:30*86400000,path:"/",domain:env.COOKIE_DOMAIN};
const emailDelivery=resendDelivery({apiKey:env.RESEND_API_KEY,from:env.RESEND_FROM,frontendUrl:env.FRONTEND_URL});
const REGISTER_WINDOW_MS=15*60*1000, REGISTER_LIMIT_PER_IP=5, REGISTER_LIMIT_PER_IDENTITY=2;
const registerAttempts=new Map<string,number[]>();
function consumeRegistrationLimit(key:string,limit:number,now=Date.now()) { const recent=(registerAttempts.get(key)??[]).filter(time=>time>now-REGISTER_WINDOW_MS); if(recent.length>=limit){registerAttempts.set(key,recent);return false;} recent.push(now);registerAttempts.set(key,recent);return true; }
function genericAccepted(res:any){return res.status(202).json({message:REGISTRATION_ACCEPTED});}

authRouter.post("/register",async(req,res,next)=>{try { const parsed=credentials.safeParse(req.body);if(!parsed.success)return res.status(400).json({error:"Invalid registration details",details:parsed.error.flatten()}); const username=parsed.data.username.trim().toLowerCase(),email=parsed.data.email.trim().toLowerCase(); const ip=req.ip||"unknown"; if(!consumeRegistrationLimit(`ip:${ip}`,REGISTER_LIMIT_PER_IP)||!consumeRegistrationLimit(`identity:${username}`,REGISTER_LIMIT_PER_IDENTITY)||!consumeRegistrationLimit(`email:${email}`,REGISTER_LIMIT_PER_IDENTITY)){res.set("Retry-After",String(REGISTER_WINDOW_MS/1000));return res.status(429).json({message:REGISTRATION_THROTTLED});}
  const result=await preparePendingRegistration(parsed.data,{findExisting:async identity=>db.user.findFirst({where:{OR:[{username:identity.username},{email:identity.email}]},select:{id:true}})??db.pendingRegistration.findFirst({where:{OR:[{username:identity.username},{email:identity.email}],consumedAt:null,expiresAt:{gt:new Date()}},select:{id:true}})},{hashPassword,createToken:createVerificationToken,hashToken:hashVerificationToken,now:()=>new Date()});
  if(!result.verificationToken||!result.pending)return genericAccepted(res);
  let pendingId:string;
  try { pendingId=(await db.pendingRegistration.create({data:result.pending})).id; } catch (error:any) { if(error?.code==="P2002") return genericAccepted(res); throw error; }
  try { await emailDelivery.sendVerification({email:result.pending.email,token:result.verificationToken}); }
  catch { await db.pendingRegistration.deleteMany({where:{id:pendingId,consumedAt:null}}); console.error(JSON.stringify({event:"registration_delivery_failed"})); return res.status(503).json({error:"Unable to send verification email. Please try again later."}); }
  await db.pendingRegistration.update({where:{id:pendingId},data:{deliveryAcceptedAt:new Date()}});
  return genericAccepted(res);
} catch(error){next(error)}});
authRouter.post("/verify-email",async(req,res)=>{const parsed=z.object({token:z.string().min(1).max(512)}).safeParse(req.body);if(!parsed.success)return res.status(400).json({error:"Invalid or expired verification link"});const verified=await verifyPendingAccount(parsed.data.token,{hashToken:hashVerificationToken,now:()=>new Date(),consumeAndVerify:async(tokenHash,now)=>db.$transaction(async tx=>{const pending=await tx.pendingRegistration.findFirst({where:{tokenHash,consumedAt:null,deliveryAcceptedAt:{not:null},expiresAt:{gt:now}}});if(!pending)return false;const consumed=await tx.pendingRegistration.updateMany({where:{id:pending.id,consumedAt:null,expiresAt:{gt:now},deliveryAcceptedAt:{not:null}},data:{consumedAt:now}});if(consumed.count!==1)return false;try { await tx.user.create({data:{username:pending.username,email:pending.email,passwordHash:pending.passwordHash,emailVerifiedAt:now}}); return true; } catch(error:any) { if(error?.code==="P2002") return false; throw error; }})});if(!verified)return res.status(400).json({error:"Invalid or expired verification link"});return res.json({message:"Email verified. You can now log in."})});
authRouter.post("/login",async(req,res)=>{const parsed=loginCredentials.safeParse(req.body);if(!parsed.success)return res.status(400).json({error:"Invalid credentials"});const identity=parsed.data.identity.toLowerCase();const found=identity.includes("@")?await db.user.findUnique({where:{email:identity}}):await db.user.findUnique({where:{username:identity}});const user=await authenticateVerifiedAccount(found,parsed.data.password,verifyPassword);if(!user)return res.status(401).json({error:"Invalid credentials"});const token=createSessionToken(),now=new Date();await db.$transaction(async tx=>{const old=req.cookies?.fitdiary_session;if(old)await tx.session.updateMany({where:{tokenHash:hashSessionToken(old),revokedAt:null},data:{revokedAt:now}});await tx.session.create({data:{userId:user.id,tokenHash:hashSessionToken(token),expiresAt:new Date(now.getTime()+SESSION_TTL_MS)}})});res.cookie("fitdiary_session",token,cookie).json({user:{id:user.id,username:user.username,email:user.email}})});
authRouter.post("/logout",async(req,res)=>{const token=req.cookies?.fitdiary_session;if(token)await db.session.updateMany({where:{tokenHash:hashSessionToken(token),revokedAt:null},data:{revokedAt:new Date()}});return res.clearCookie("fitdiary_session",cookie).status(204).end()});
authRouter.post("/forgot-password",async(req,res)=>{const parsed=z.object({email:z.string().trim().email()}).safeParse(req.body);if(parsed.success){const result=await requestPasswordReset(parsed.data.email,{now:()=>new Date(),findVerifiedUser:email=>db.user.findFirst({where:{email,emailVerifiedAt:{not:null}},select:{id:true}}),store:async data=>{await db.passwordResetToken.create({data})}});if(result.resetToken)await emailDelivery.sendPasswordReset({email:parsed.data.email,token:result.resetToken})}return res.status(202).json({message:PASSWORD_RESET_ACCEPTED})});
authRouter.post("/reset-password",async(req,res)=>{const parsed=z.object({token:z.string().min(1).max(512),password:z.string().min(10).max(128)}).safeParse(req.body);if(!parsed.success)return res.status(400).json({error:PASSWORD_RESET_INVALID});const changed=await resetPassword(parsed.data.token,parsed.data.password,{now:()=>new Date(),hashPassword,consumeUpdateAndRevoke:async({tokenHash,passwordHash,now})=>db.$transaction(async tx=>{const token=await tx.passwordResetToken.findFirst({where:{tokenHash,consumedAt:null,expiresAt:{gt:now}},select:{id:true,userId:true}});if(!token)return false;const consumed=await tx.passwordResetToken.updateMany({where:{id:token.id,consumedAt:null,expiresAt:{gt:now}},data:{consumedAt:now}});if(consumed.count!==1)return false;await tx.user.update({where:{id:token.userId},data:{passwordHash}});await tx.session.updateMany({where:{userId:token.userId,revokedAt:null},data:{revokedAt:now}});return true})});if(!changed)return res.status(400).json({error:PASSWORD_RESET_INVALID});return res.json({message:"Password reset. You can now log in."})});
authRouter.get("/me",requireUser,async(req:AuthedRequest,res)=>{const user=await db.user.findUnique({where:{id:req.userId},select:{id:true,username:true,email:true,displayName:true,calorieGoal:true,proteinGoal:true,carbGoal:true,fatGoal:true,waterGoalMl:true,units:true,onboardedAt:true}});if(!user)return res.json({user:null});const {onboardedAt,...rest}=user;res.json({user:{...rest,onboarded:Boolean(onboardedAt)}})});
