import { Router } from "express";
import { z } from "zod";
import { db } from "../db.js";
import { dayBounds, parseDay } from "../daySummary.js";
import { requireUser, type AuthedRequest } from "../middleware/requireUser.js";
import multer from "multer";
import { contentTypeFor,detectImage,loadPhoto,MAX_PHOTO_BYTES,photoObjectKey,removePhoto,serializeByKey,storePhoto } from "../photoStorage.js";
import { env } from "../config.js";
import { Prisma } from "@prisma/client";

export const diaryRouter=Router(); diaryRouter.use(requireUser);
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:MAX_PHOTO_BYTES,files:1}});
const itemSchema=z.object({foodId:z.string().optional(),name:z.string().trim().min(1).max(200),servings:z.number().positive().max(1000).default(1),servingLabel:z.string().trim().min(1).max(100).default("serving"),calories:z.number().nonnegative().max(100000),proteinG:z.number().nonnegative().max(10000).default(0),carbsG:z.number().nonnegative().max(10000).default(0),fatG:z.number().nonnegative().max(10000).default(0)});
const entrySchema=z.object({date:z.string().transform(parseDay),mealType:z.enum(["BREAKFAST","LUNCH","DINNER","SNACK"]),title:z.string().trim().min(1).max(120).optional(),notes:z.string().trim().max(1000).optional(),items:z.array(itemSchema).min(1).max(100)});
const dates=(date:string)=>{const {start,end}=dayBounds(date);return {gte:start,lt:end};};
async function trustedItems(userId:string,items:z.infer<typeof itemSchema>[]){
  const ids=[...new Set(items.flatMap(item=>item.foodId?[item.foodId]:[]))];
  const foods=ids.length?await db.food.findMany({where:{id:{in:ids},OR:[{ownerId:null,verified:true,source:"VERIFIED"},{ownerId:userId,source:"CUSTOM"}]},select:{id:true,name:true,servingLabel:true,calories:true,proteinG:true,carbsG:true,fatG:true}}):[];
  if(foods.length!==ids.length)return null;const byId=new Map(foods.map(food=>[food.id,food]));
  return items.map(item=>item.foodId?{...byId.get(item.foodId)!,foodId:item.foodId,servings:item.servings}:item);
}
const publicEntry=<T extends {photoKey:string|null}>(entry:T)=>{const {photoKey,...rest}=entry;return {...rest,hasPhoto:Boolean(photoKey)}};
const jsonValue=(value:Prisma.JsonValue|null):Prisma.InputJsonValue|typeof Prisma.DbNull=>value===null?Prisma.DbNull:value;

diaryRouter.get("/",async(req:AuthedRequest,res)=>{const date=parseDay(req.query.date);const entries=await db.diaryEntry.findMany({where:{userId:req.userId,date:dates(date)},include:{items:true},orderBy:{createdAt:"asc"}});res.json({date,entries:entries.map(publicEntry)})});
diaryRouter.post("/",async(req:AuthedRequest,res)=>{const body=entrySchema.parse(req.body);const items=await trustedItems(req.userId!,body.items);if(!items)return res.status(400).json({error:"Invalid food reference"});const entry=await db.diaryEntry.create({data:{userId:req.userId!,date:new Date(`${body.date}T00:00:00.000Z`),mealType:body.mealType,title:body.title,notes:body.notes,items:{create:items}},include:{items:true}});res.status(201).json({entry:publicEntry(entry)})});
diaryRouter.put("/:id",async(req:AuthedRequest,res)=>{const body=entrySchema.parse(req.body);const found=await db.diaryEntry.findFirst({where:{id:String(req.params.id),userId:req.userId},select:{id:true}});if(!found)return res.status(404).json({error:"Entry not found"});const items=await trustedItems(req.userId!,body.items);if(!items)return res.status(400).json({error:"Invalid food reference"});const entry=await db.$transaction(async tx=>{await tx.diaryItem.deleteMany({where:{diaryEntryId:found.id}});return tx.diaryEntry.update({where:{id:found.id},data:{date:new Date(`${body.date}T00:00:00.000Z`),mealType:body.mealType,title:body.title,notes:body.notes,items:{create:items}},include:{items:true}})});res.json({entry:publicEntry(entry)})});
diaryRouter.delete("/:id",async(req:AuthedRequest,res)=>{await serializeByKey(String(req.params.id),async()=>{const found=await db.diaryEntry.findFirst({where:{id:String(req.params.id),userId:req.userId},select:{id:true,photoKey:true}});if(!found)return res.status(404).json({error:"Entry not found"});let photo:Buffer|undefined;if(found.photoKey){try{photo=await loadPhoto(env.UPLOAD_DIR,found.photoKey);await removePhoto(env.UPLOAD_DIR,found.photoKey)}catch{return res.status(500).json({error:"Photo cleanup failed; diary entry was not deleted"})}}try{await db.diaryEntry.delete({where:{id:found.id}})}catch(error){if(found.photoKey&&photo)await storePhoto(env.UPLOAD_DIR,found.photoKey,photo);throw error}return res.status(204).end()})});
diaryRouter.put("/:id/photo",upload.single("photo"),async(req:AuthedRequest,res)=>{if(!req.file)return res.status(400).json({error:"Photo is required"});const ext=detectImage(req.file.mimetype,req.file.buffer);if(!ext)return res.status(415).json({error:"Photo must be a valid JPEG, PNG, or WebP"});await serializeByKey(String(req.params.id),async()=>{const found=await db.diaryEntry.findFirst({where:{id:String(req.params.id),userId:req.userId},select:{id:true,photoKey:true,photoUrl:true,analysisStatus:true,aiRawEstimate:true}});if(!found)return res.status(404).json({error:"Entry not found"});const key=photoObjectKey(req.userId!,ext);await storePhoto(env.UPLOAD_DIR,key,req.file!.buffer);try{await db.diaryEntry.update({where:{id:found.id},data:{photoKey:key,photoUrl:null,analysisStatus:"NOT_REQUESTED",aiRawEstimate:Prisma.DbNull}})}catch(e){await removePhoto(env.UPLOAD_DIR,key);throw e}try{if(found.photoKey)await removePhoto(env.UPLOAD_DIR,found.photoKey)}catch{await db.diaryEntry.update({where:{id:found.id},data:{photoKey:found.photoKey,photoUrl:found.photoUrl,analysisStatus:found.analysisStatus,aiRawEstimate:jsonValue(found.aiRawEstimate)}});await removePhoto(env.UPLOAD_DIR,key).catch(()=>undefined);return res.status(500).json({error:"Photo replacement cleanup failed; previous photo was preserved"})}return res.json({photoPath:`/diary/${found.id}/photo`,analysis:{enabled:false,status:"NOT_REQUESTED"}})})});
diaryRouter.get("/:id/photo",async(req:AuthedRequest,res)=>{const found=await db.diaryEntry.findFirst({where:{id:String(req.params.id),userId:req.userId},select:{photoKey:true}});if(!found?.photoKey)return res.status(404).json({error:"Photo not found"});try{const data=await loadPhoto(env.UPLOAD_DIR,found.photoKey);res.set("Content-Type",contentTypeFor(found.photoKey));res.set("Cache-Control","private, no-store");res.send(data)}catch(e:any){if(e?.code==="ENOENT")return res.status(404).json({error:"Photo not found"});throw e}});
diaryRouter.delete("/:id/photo",async(req:AuthedRequest,res)=>{await serializeByKey(String(req.params.id),async()=>{const found=await db.diaryEntry.findFirst({where:{id:String(req.params.id),userId:req.userId},select:{id:true,photoKey:true,photoUrl:true,analysisStatus:true,aiRawEstimate:true}});if(!found)return res.status(404).json({error:"Entry not found"});await db.diaryEntry.update({where:{id:found.id},data:{photoKey:null,photoUrl:null,analysisStatus:"NOT_REQUESTED",aiRawEstimate:Prisma.DbNull}});try{if(found.photoKey)await removePhoto(env.UPLOAD_DIR,found.photoKey)}catch{await db.diaryEntry.update({where:{id:found.id},data:{photoKey:found.photoKey,photoUrl:found.photoUrl,analysisStatus:found.analysisStatus,aiRawEstimate:jsonValue(found.aiRawEstimate)}});return res.status(500).json({error:"Photo cleanup failed; diary record was not changed"})}return res.status(204).end()})});
