"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { createTrackingEntry, deleteTrackingEntry, getWeightHistory, isoDay, updateTrackingEntry, WeightEntry } from "../../../lib/tracking";
import { EditIcon, PlusIcon, ScaleIcon, TargetIcon, TrashIcon } from "../../../components/UiIcons";

const ago=(days:number)=>{const d=new Date();d.setDate(d.getDate()-days);return isoDay(d)};
const dateLabel=(date:string)=>new Intl.DateTimeFormat("en",{month:"short",day:"numeric"}).format(new Date(date));

function WeightChart({entries}:{entries:WeightEntry[]}){
 const points=useMemo(()=>{if(!entries.length)return[];const values=entries.map(e=>e.weightKg),min=Math.min(...values),max=Math.max(...values),span=Math.max(max-min,1);return entries.map((e,i)=>({x:entries.length===1?50:5+i/(entries.length-1)*90,y:85-(e.weightKg-min)/span*65,e}))},[entries]);
 const path=points.map((p,i)=>`${i?"L":"M"} ${p.x} ${p.y}`).join(" ");
 if(!points.length)return <div className="chart-empty"><ScaleIcon/><p>Your weight trend will appear after your first check-in.</p></div>;
 return <div className="weight-chart"><svg viewBox="0 0 100 100" preserveAspectRatio="none" role="img" aria-label="Weight trend chart"><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#6c63ff" stopOpacity=".28"/><stop offset="1" stopColor="#6c63ff" stopOpacity="0"/></linearGradient></defs>{[20,40,60,80].map(y=><line key={y} x1="0" x2="100" y1={y} y2={y} className="chart-grid"/>)}<path d={`${path} L ${points.at(-1)!.x} 95 L ${points[0].x} 95 Z`} fill="url(#area)"/><path d={path} className="chart-line" vectorEffect="non-scaling-stroke"/>{points.map(p=><circle key={p.e.id} cx={p.x} cy={p.y} r="1.6" className="chart-dot" vectorEffect="non-scaling-stroke"/>)}</svg><div className="chart-axis"><span>{dateLabel(entries[0].date)}</span><span>{dateLabel(entries.at(-1)!.date)}</span></div></div>
}

export default function Progress(){
 const[from,setFrom]=useState(()=>ago(89)),[to,setTo]=useState(()=>isoDay(new Date())),[entries,setEntries]=useState<WeightEntry[]>([]),[editing,setEditing]=useState<WeightEntry|null>(null),[creating,setCreating]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(""),[message,setMessage]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");try{setEntries((await getWeightHistory(from,to)).entries)}catch(e){setError(e instanceof Error?e.message:"Could not load history")}finally{setLoading(false)}},[from,to]);useEffect(()=>{void load()},[load]);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,f=new FormData(form),body={date:f.get("date"),weightKg:Number(f.get("weightKg")),notes:f.get("notes")||undefined};try{editing?await updateTrackingEntry("weight",editing.id,body):await createTrackingEntry("weight",body);setEditing(null);setCreating(false);setMessage(editing?"Check-in updated":"New weight recorded");await load()}catch(e){setError(e instanceof Error?e.message:"Could not save weight")}}
 const first=entries[0],last=entries.at(-1),change=first&&last?last.weightKg-first.weightKg:0,average=entries.length?entries.reduce((n,e)=>n+e.weightKg,0)/entries.length:0;
 return <main className="product-page progress-page">
  <section className="page-heading"><div><p className="eyebrow">Your journey</p><h1>Progress</h1><p>Small check-ins make the long-term trend visible.</p></div><button className="primary-action" onClick={()=>{setEditing(null);setCreating(true)}}><PlusIcon/> Log weight</button></section>
  {error&&<p className="alert-card" role="alert">{error}</p>}{message&&<p className="success-card" role="status">{message}</p>}
  <div className="metric-grid"><article className="metric-card featured"><span className="metric-icon"><ScaleIcon/></span><div><p>Latest weight</p><strong>{last?last.weightKg.toFixed(1):"—"}<small>{last?" kg":""}</small></strong><span>{last?dateLabel(last.date):"No check-ins yet"}</span></div></article><article className="metric-card"><span className={`metric-icon ${change<=0?"positive":"warm"}`}><TargetIcon/></span><div><p>Change</p><strong>{entries.length>1?`${change>0?"+":""}${change.toFixed(1)}`:"—"}<small>{entries.length>1?" kg":""}</small></strong><span>in selected range</span></div></article><article className="metric-card"><span className="metric-icon soft"><ScaleIcon/></span><div><p>Average</p><strong>{entries.length?average.toFixed(1):"—"}<small>{entries.length?" kg":""}</small></strong><span>{entries.length} check-ins</span></div></article></div>
  <section className="chart-card"><header><div><h2>Weight trend</h2><p>{entries.length?`${dateLabel(entries[0].date)} – ${dateLabel(entries.at(-1)!.date)}`:"Your last 90 days"}</p></div><div className="range-fields"><label>From<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>To<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label></div></header>{loading?<div className="chart-empty">Loading trend…</div>:<WeightChart entries={entries}/>}</section>
  <section className="history-card"><div className="section-heading"><div><h2>Check-in history</h2><p>Your recorded weights and notes</p></div></div>{!loading&&entries.length===0?<div className="visual-empty compact"><div className="empty-illustration"><ScaleIcon/><span>+</span></div><h3>Start your trend</h3><p>Log your weight today. Consistency matters more than daily changes.</p><button className="primary-action" onClick={()=>setCreating(true)}>Add first check-in</button></div>:<div className="history-list">{[...entries].reverse().map((x,i)=><article key={x.id}><div className="timeline-marker"><span></span>{i<entries.length-1&&<i/>}</div><div><strong>{dateLabel(x.date)}</strong><p>{x.notes||"Weight check-in"}</p></div><b>{x.weightKg.toFixed(1)} <small>kg</small></b><div className="row-actions"><button aria-label="Edit check-in" onClick={()=>{setEditing(x);setCreating(true)}}><EditIcon/></button><button aria-label="Delete check-in" onClick={async()=>{await deleteTrackingEntry("weight",x.id);setMessage("Check-in removed");await load()}}><TrashIcon/></button></div></article>)}</div>}</section>
  {creating&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget){setCreating(false);setEditing(null)}}}><section className="sheet-modal small" role="dialog" aria-modal="true" aria-labelledby="weight-title"><header><div><p className="eyebrow">Progress check-in</p><h2 id="weight-title">{editing?"Edit weight":"Log your weight"}</h2></div><button className="icon-close" aria-label="Close" onClick={()=>{setCreating(false);setEditing(null)}}>×</button></header><form className="modern-form" onSubmit={save} key={editing?.id||"new"}><label>Date<input name="date" type="date" defaultValue={editing?editing.date.slice(0,10):to} required/></label><label>Weight (kg)<div className="unit-input"><input name="weightKg" type="number" min="1" max="500" step="0.01" defaultValue={editing?.weightKg} required/><span>kg</span></div></label><label>How are you feeling? <span className="optional">Optional</span><textarea name="notes" defaultValue={editing?.notes||""} placeholder="Energy, sleep, wins…"/></label><button className="primary-action full">{editing?"Save changes":"Record check-in"}</button></form></section></div>}
 </main>
}
